INSERT INTO `dba5013`.`Countries` (
`Country` ,
`Continent` ,
`PolygonName`
)
VALUES
	('Algeria', 'Africa', 'algeria'),
    ('Angola', 'Africa', 'angola'),
    ('Benin', 'Africa', 'benin'),
    ('Botswana', 'Africa', 'botswana'),
    ('Burkina', 'Africa', 'burkina'),
    ('Burundi', 'Africa', 'burundi'),
    ('Cameroon', 'Africa', 'cameroon'),
    ('Cape Verde', 'Africa', 'cape_verde'),
    ('Central African Republic', 'Africa', 'central_african_republic'),
    ('Chad', 'Africa', 'chad'),
    ('Comoros', 'Africa', 'comoros'),
    ('Congo', 'Africa', 'congo'),
    ('Democratic Republic of Congo', 'Africa', 'democratic_republic_of_congo'),
    ('Djibouti', 'Africa', 'djibouti'),
    ('Egypt', 'Africa', 'egypt'),
    ('Equatorial Guinea', 'Africa', 'equatorial_guinea'),
    ('Eritrea', 'Africa', 'eritrea'),
    ('Ethiopia', 'Africa', 'ethiopia'),
    ('Gabon', 'Africa', 'gabon'),
    ('Gambia', 'Africa', 'gambia'),
    ('Ghana', 'Africa', 'ghana'),
    ('Guinea', 'Africa', 'guinea'),
    ('Guinea Bissau', 'Africa', 'guinea_bissau'),
    ('Ivory Coast', 'Africa', 'ivory_coast'),
    ('Kenya', 'Africa', 'kenya'),
    ('Lesotho', 'Africa', 'lesotho'),
    ('Liberia', 'Africa', 'liberia'),
    ('Libya', 'Africa', 'libya'),
    ('Madagascar', 'Africa', 'madagascar'),
    ('Malawi', 'Africa', 'malawi'),
    ('Mali', 'Africa', 'mali'),
    ('Mauritania', 'Africa', 'mauritania'),
    ('Mauritius', 'Africa', 'mauritius'),
    ('Morocco', 'Africa', 'morocco'),
    ('Mozambique', 'Africa', 'mozambique'),
    ('Namibia', 'Africa', 'namibia'),
    ('Niger', 'Africa', 'niger'),
    ('Nigeria', 'Africa', 'nigeria'),
    ('Rwanda', 'Africa', 'rwanda'),
    ('Sao Tome and Principe', 'Africa', 'sao_tome_and_principe'),
    ('Senegal', 'Africa', 'senegal'),
    ('Seychelles', 'Africa', 'seychelles'),
    ('Sierra Leone', 'Africa', 'sierra_leone'),
    ('Somalia', 'Africa', 'somalia'),
    ('South Africa', 'Africa', 'south_africa'),
    ('South Sudan', 'Africa', 'south_sudan'),
    ('Sudan', 'Africa', 'sudan'),
    ('Swaziland', 'Africa', 'swaziland'),
    ('Tanzania', 'Africa', 'tanzania'),
    ('Togo', 'Africa', 'togo'),
    ('Tunisia', 'Africa', 'tunisia'),
    ('Uganda', 'Africa', 'uganda'),
    ('Zambia', 'Africa', 'zambia'),
    ('Zimbabwe', 'Africa', 'zimbabwe');
