INSERT INTO `dba5013`.`Countries` (
`Country` ,
`Continent` ,
`PolygonName`
)
VALUES
    ('Afghanistan', 'Asia', 'afghanistan'),
    ('Bahrain', 'Asia', 'bahrain'),
    ('Bangladesh', 'Asia', 'bangladesh'),
    ('Bhutan', 'Asia', 'bhutan'),
    ('Brunei', 'Asia', 'brunei'),
    ('Burma', 'Asia', 'burma'),
    ('Cambodia', 'Asia', 'cambodia'),
    ('China', 'Asia', 'china'),
    ('East Timor', 'Asia', 'east_timor'),
    ('India', 'Asia', 'india'),
    ('Indonesia', 'Asia', 'indonesia'),
    ('Iran', 'Asia', 'iran'),
    ('Iraq', 'Asia', 'iraq'),
    ('Israel', 'Asia', 'israel'),
    ('Japan', 'Asia', 'japan'),
    ('Jordan', 'Asia', 'jordan'),
    ('Kazakhstan', 'Asia', 'kazakhstan'),
    ('North Korea', 'Asia', 'north_korea'),
    ('South Korea', 'Asia', 'south_korea'),
    ('Kuwait', 'Asia', 'kuwait'),
    ('Kyrgyzstan', 'Asia', 'kyrgyzstan'),
    ('Laos', 'Asia', 'laos'),
    ('Lebanon', 'Asia', 'lebanon'),
    ('Malaysia', 'Asia', 'malaysia'),
    ('Maldives', 'Asia', 'maldives'),
    ('Mongolia', 'Asia', 'mongolia'),
    ('Nepal', 'Asia', 'nepal'),
    ('Oman', 'Asia', 'oman'),
    ('Pakistan', 'Asia', 'pakistan'),
    ('Philippines', 'Asia', 'philippines'),
    ('Qatar', 'Asia', 'qatar'),
    ('Russia', 'Asia', 'russia'),
    ('Saudi Arabia', 'Asia', 'saudi_arabia'),
    ('Singapore', 'Asia', 'singapore'),
    ('Sri Lanka', 'Asia', 'sri_lanka'),
    ('Syria', 'Asia', 'syria'),
    ('Tajikistan', 'Asia', 'tajikistan'),
    ('Thailand', 'Asia', 'thailand'),
    ('Turkey', 'Asia', 'turkey'),
    ('Turkmenistan', 'Asia', 'turkmenistan'),
    ('United Arab Emirates', 'Asia', 'united_arab_emirates'),
    ('Uzbekistan', 'Asia', 'uzbekistan'),
    ('Vietnam', 'Asia', 'vietnam'),
    ('Yemen', 'Asia', 'yemen');