INSERT INTO `dba5013`.`Countries` (
`Country` ,
`Continent` ,
`PolygonName`
)
VALUES
    ('Albania', 'Europe', 'albania'),
    ('Andorra', 'Europe', 'andorra'),
    ('Armenia', 'Europe', 'armenia'),
    ('Austria', 'Europe', 'austria'),
    ('Azerbaijan', 'Europe', 'azerbaijan'),
    ('Belarus', 'Europe', 'belarus'),
    ('Belgium', 'Europe', 'belgium'),
    ('Bosnia and Herzegovina', 'Europe', 'bosnia_and_herzegovina'),
    ('Bulgaria', 'Europe', 'bulgaria'),
    ('Croatia', 'Europe', 'croatia'),
    ('Cyprus', 'Europe', 'cyprus'),
    ('Czech Republic', 'Europe', 'czech_republic'),
    ('Denmark', 'Europe', 'denmark'),
    ('Estonia', 'Europe', 'estonia'),
    ('Finland', 'Europe', 'finland'),
    ('France', 'Europe', 'france'),
    ('Georgia', 'Europe', 'georgia'),
    ('Germany', 'Europe', 'germany'),
    ('Greece', 'Europe', 'greece'),
    ('Hungary', 'Europe', 'hungary'),
    ('Iceland', 'Europe', 'iceland'),
    ('Ireland', 'Europe', 'ireland'),
    ('Italy', 'Europe', 'italy'),
    ('Latvia', 'Europe', 'latvia'),
    ('Liechtenstein', 'Europe', 'liechtenstein'),
    ('Lithuania', 'Europe', 'lithuania'),
    ('Luxembourg', 'Europe', 'luxembourg'),
    ('Macedonia', 'Europe', 'macedonia'),
    ('Malta', 'Europe', 'malta'),
    ('Moldova', 'Europe', 'moldova'),
    ('Monaco', 'Europe', 'monaco'),
    ('Montenegro', 'Europe', 'montenegro'),
    ('Netherlands', 'Europe', 'netherlands'),
    ('Norway', 'Europe', 'norway'),
    ('Poland', 'Europe', 'poland'),
    ('Portugal', 'Europe', 'portugal'),
    ('Romania', 'Europe', 'romania'),
    ('San Marino', 'Europe', 'san_marino'),
    ('Serbia', 'Europe', 'serbia'),
    ('Slovakia', 'Europe', 'slovakia'),
    ('Slovenia', 'Europe', 'solovenia'),
    ('Spain', 'Europe', 'spain'),
    ('Sweden', 'Europe', 'sweden'),
    ('Switzerland', 'Europe', 'switzerland'),
    ('Ukraine', 'Europe', 'ukraine'),
    ('United Kingdom', 'Europe', 'united_kingdom'),
    ('Vatican City', 'Europe', 'vatican_city');
